site_name: backend
site_description: Simple ToDo list application
repo_url: https://github.com/lexvel/edicasoft-assignment
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/lexvel">lexvel</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
    - Tasks: 'api/tasks.md'
